version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: task_manager_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: taskmanager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: task_manager_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # این متغیرها تنظیمات داخل فایل env. شما را نادیده می‌گیرند و برای داکر تنظیم می‌شوند
      APP_PORT: 8080
      DB_HOST: db         # نام این فیلد باید دقیقا برابر با نام سرویس دیتابیس در خط 4 باشد
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: taskmanager_db
      DB_CHARSET: utf8

      GOPROXY: "https://goproxy.cn,direct"

    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  postgres_data:
